version: '3'
services:
  postgis:
    container_name: world_map_db
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=WorldMapProject
    ports:
      - "8001:5432"