version: '3'
services:
  postgis:
    container_name: world_map_test
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DB_NAME}
    ports:
      - "${IMAGE_PORT}:5432"